<div class="box">
    <div class="container">
        <div class="top-header">
            <span><a href="index.php" class="register">Založit účet</a></span>
            <span><a href="main_no_login.php" class="continue">Pokračovat nepřihlášený</a></span>
            
            <header>Přihlášení</header>
        </div>
        <form method="post">
            <div class="input-field">
                <input type="text" class="input" name="login" placeholder="Uživatelské jméno" required>
            </div>

            <div class="input-field">
                <input type="password" class="input" name="password" placeholder="Heslo" required>
            </div>

            <div class="input-field">
                <input type="submit" class="submit" value="Přihlásit se">
            </div>

            <div class="bottom">
                <div class="left">
                    <input type="checkbox" id="check" name="checkbox">
                    <label for="check">Zapamatovat přihlašovací údaje</label>
                </div>
            </div>
        </form>
    </div>
</div>