<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="<?= $CSSpath ?>">
        <title>Tréninkový plán<?= $title ?></title>
    </head>

    <body>
        <div class="user">
            <nav>
                <ul>
                    <li><a href="main_no_login.php">Tréninkový plán</a></li>
                    <li><a href="exercises_no_login.php">Seznam cviků</a></li>
                </ul>
        
                <img src="img/question_mark_person.jpg" class="user-pic" onclick="toggleMenu()" alt="Otevřít menu">
        
                <div class="sub-menu-wrap" id="subMenu">
                    <div class="sub-menu">
                        <div class="user-info">
                            <img src="img/question_mark_person.jpg" class="random-class" alt="Profilový obrázek">
                            <h3>Nepřihlášený uživatel</h3>
                        </div>

                        <hr>

                        <a href="create_account.php" class="sub-menu-link">
                            <img src="img/logout.png" class="random-class" alt="Odhlásit se">
                            <p>Vytvořit účet</p>
                            <span>></span>
                        </a>
                    </div>
                </div>
            </nav>

            <script>
                let subMenu = document.getElementById("subMenu")

                function toggleMenu() {
                    subMenu.classList.toggle("open-menu")
                }
            </script>
        </div>